name: CI

on:
  push:
    branches:
      - main


env:
 
  PATH_BUILD_WEB: ./apps/web/dist
  PATH_BUILD_WEB_FUNCTIONS: ./apps/web/.netlify/functions-internal

  CACHE_PATHS_BUILD: |
  
    ./apps/web/.netlify
    ./apps/web/dist
   
  CACHE_KEY_BUILD: build-${{ github.sha }}
# To use Remote Caching, uncomment the next lines and follow the steps below.
#  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
#  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  build:
    name: Build 🏗️
    runs-on: ubuntu-latest
    environment:
      name: this
      url: https://github.com/ka9an/denopendabot

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/workflows/setup

      - name: Build
        run: pnpm build

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_PATHS_BUILD }}
          key: ${{ env.CACHE_KEY_BUILD }}









      - name: Deploy to Netlify using their CLI
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=${{ env.PATH_BUILD_WEB }} --functions=${{ env.PATH_BUILD_WEB_FUNCTIONS }} -p
        env:
          NETLIFY_SITE_ID: cc097bcd-09d1-494e-873f-708b6620a87d
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

